export const MimiLinks = [
  {
    name: 'Introduction Mimi',
    content: 'Les spécialités de Mimi',
    require: 1,
    id: '0001',
    quizz: false,
  },
  {
    name: 'Chats errants – abandons, chats perdus',
    content: 'Lien',
    require: 4,
    id: '0002',
    quizz: true,
  },
  {
    name: 'Risques pour les chats errants',
    content: 'Lien',
    require: 6,
    id: '0003',
    quizz: false,
  },
  {
    name: 'Nuisances causées par les chats errants',
    content: 'Yes',
    require: 9,
    id: '0004',
    quizz: true,
  },
  {
    name: 'Qui est responsable ? ',
    content: 'Yes',
    require: 10,
    id: '0005',
    quizz: false,
  },
  {
    name: 'Une solution : La stérilisation ',
    content: 'Yes',
    require: 13,
    id: '0006',
    quizz: true,
  },
  {
    name: 'L’action des associations de protection animale',
    content: 'Yes',
    require: 15,
    id: '0007',
    quizz: true,
  },
];

export const NewtLinks = [
  {
    name: 'Introduction Newt',
    content: 'Les spécialités de Newt',
    require: 1,
    id: '0001',
    quizz: false,
  },
  {
    name: 'Le chat, proie et prédateur à la fois',
    content: 'Les spécialités de Newt',
    require: 2,
    id: '0002',
    quizz: false,
  },
  {
    name: 'La journée d’un chat',
    content: 'Les spécialités de Newt',
    require: 5,
    id: '0003',
    quizz: true,
  },
  {
    name: 'Le régime alimentaire du chat',
    content: '',
    require: 7,
    id: '0004',
    quizz: false,
  },
  {
    name: 'La santé des chats (croissance, maladies, plantes toxiques…)',
    content: '',
    require: 10,
    id: '0005',
    quizz: true,
  },
  {
    name: 'Les chats entre eux ',
    content: '',
    require: 12,
    id: '0006',
    quizz: false,
  },
  {
    name: 'Les chats et les humains ',
    content: '',
    require: 15,
    id: '0007',
    quizz: true,
  },
];

export const NeelixLinks = [
  {
    name: 'Introduction Neelix',
    content: 'Les spécialités de Neelix',
    require: 1,
    id: '0001',
    quizz: false,
  },
  {
    name: 'Adopter un chat : pourquoi, où, comment ? ',
    content: '',
    require: 4,
    id: '0002',
    quizz: true,
  },
  {
    name: 'Chaton ou chat adulte ?',
    content: '',
    require: 5,
    id: '0003',
    quizz: false,
  },
  {
    name: 'Chat d’intérieur, chat de jardin… les pour et contre',
    content: '',
    require: 7,
    id: '0004',
    quizz: false,
  },
  {
    name: 'Equipement de base ',
    content: '',
    require: 10,
    id: '0005',
    quizz: true,
  },
  {
    name: 'Budget estimatif ',
    content: '',
    require: 13,
    id: '0006',
    quizz: true,
  },
  {
    name: 'Le suivi vétérinaire : indispensable ',
    content: '',
    require: 15,
    id: '0007',
    quizz: false,
  },
  {
    name: 'Les petits plus pour mieux servir votre chat ',
    content: '',
    require: 19,
    id: '0008',
    quizz: true,
  },
];
